#!/bin/sh
exec su -s /bin/sh www-data -c "/venv/bin/celery --config=vgmdb.celery --app=vgmdb.celery worker --max-tasks-per-child=10000 --time-limit=300 --concurrency=10 --pool=prefork --hostname=vgmdb-search.%h --queues=search"
