#!/bin/sh
exec su -s /bin/sh www-data -c "/usr/local/bin/celery worker --maxtasksperchild=1000 --time-limit=300 --concurrency=3 --pool=threads --app=vgmdb --workdir=/ --config=celery --hostname=vgmdb-background.%h --queues=celery,sellers,background"
