#!/bin/sh
cd /; exec uwsgi --plugins python,gevent --uid www-data -p 1 --max-worker-lifetime 600 --max-requests 10000 --gevent 200 --gevent-monkey-patch -s /tmp/uwsgi.sock --plugins=python --module wsgi --callable application
