AMAZON_ACCESS_KEY_ID = 'ABCV32..'
AMAZON_SECRET_ACCESS_KEY = 'ABCpqb24..'
AMAZON_ASSOCIATE_TAG = 'mytag0-60'

# American
ITUNES_AFFILIATE_ID = 'id'
# European
ITUNES_TD_PROGRAM_ID = 'id'
ITUNES_TD_WEBSITE_ID = 'id'

DISCOGS_KEY = 'jF..'
DISCOGS_SECRET = 'hY..'

RDIO_KEY = 'g6..'
RDIO_SECRET = '8x..'
